server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:8081
          predicates:
            - Path=/book/**
        - id: student-service
          uri: http://localhost:8082
          predicates:
            - Path=/student/**
        - id: borrow-issue-service
          uri: http://localhost:8083
          predicates:
            - Path=/borrow/**
